import type { Metadata } from 'next'

import '../../styles/globals.css'
import HeaderNav from './components/navbar/HeaderNav';
import SelectNav from './components/navbar/SelectNav';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body>
                <div className="flex h-screen flex-col md:flex-row md:overflow-hidden text-wrap">
                    <div className="w-full flex-none md:w-64 bg-slate-500 overflow-auto">
                        <HeaderNav />
                        <SelectNav/>
                    </div>
                    <div className="flex-grow md:overflow-auto">{children}</div>
                </div>
            </body>
        </html>

    );
}